logging:
  pattern:
    console: "\r%clr([%d{yyyy/MM/dd-HH:mm:ss}]){green} %clr([%-4level]){aqua} %clr(-){grey} %clr(%msg%n){white}"
    file: "\r%clr([%d{yyyy/MM/dd-HH:mm:ss}]){green} %clr([%-4level]){aqua} %clr(-){grey} %clr(%msg%n){white}"
  level:
    o.apache.catalina.core: false
    org.apache.catalina.core: false
    o.a.c.c: false